config/routes.rb
Rails.application.routes.draw do
  resources :poems
  root 'poems#index'

end

app/models/poem.rb
class Poem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
require "google-search"
require "marky_markov"
require "sanitize"
require "wikipedia"
class PoemsController < ApplicationController
  include PoemsHelper
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
      poem_params = generate_poem
      if poem_params
        @poem = Poem.new(poem_params)

        respond_to do |format|
          if @poem.save
            format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
            format.json { render :show, status: :created, location: @poem }
          else
            format.html { render :new }
            format.json { render json: @poem.errors, status: :unprocessable_entity }
          end
        end
      else
        @poem = Poem.new
        respond_to do |format|
          format.html { render :new }
          format.json { render json: "Search returned nothing", status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:lexicon, :poem, :search, :second_search, :ss, :deep)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
  def generate_poem
    search = poem_params[:search]
    lex = ""
    lex += get_text(search)
    lex += get_text(poem_params[:second_search])
    lex = Sanitize.fragment(lex)
    return nil if lex.empty?
    poem = ""
 #   mark = MarkyMarkov::TemporaryDictionary.new
    mark = MarkovChains::Generator.new(lex)
 #   mark.parse_string lex
    #random_range(6, 15).times do 
    #  if rand % 2 
    #    poem += mark.generate_n_words random_range(3, 8)
    #  else 
   #     poem += mark.generate_1_sentence
  #    end
    poem = mark.get_sentences(random_range(6, 12)).join(" || ")
    #  poem += " || "
    #end
    return {poem: poem, lexicon: lex, search: search, ss: poem_params[:second_search].present?, second_search: poem_params[:second_search]}
  end

  def get_text(query)
    return "" if query.empty?
    return google_search(query) + wikipedia_search(query)
  end

  def google_search(query)
    t= ""    
    Google::Search::News.new(query: query).each_with_index do |q,i|
      t += q.content
    end
    return t
  end

  def wikipedia_search(query)
    p = Wikipedia.find(query)
    begin
      return p.summary.delete('\n')
    rescue
      return ""
    end
  end

  def random_range(start, stop)
    return start + rand(stop-start)
  end

  def poem_title(poem)
    t = poem.search
    t += " & #{poem.second_search}" if poem.ss
    return t
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poetry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Poems",   root_url %></li>
            <li><%= link_to "About",   '#' %></li>
            <li><%= link_to "New Poem", new_poem_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :search %><br>
    <%= f.text_field :search %>
  </div>
  <div class="field">
    <%= f.label :second_search, "Second Search (Optional)" %><br>
    <%= f.text_field :second_search %>
  </div>
  <div class="field>
    <%= f.label :deep, "Deep Search? (May take longer to generate)" %>
    <%= f.check_box :deep %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/_poem.html.erb
<div align="center">
  <% if index %>
    <h3><%= link_to poem_title(poem), poem %></h3>
  <% else %>
    <h1><%= poem_title(poem) %></h1>
  <% end %>

  <p><% poem.poem.split(" || ").each do |line| %>
    <%= line %>
    <br>
  <% end %>
</div>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>
<div align="center">
<%= form_for(@poem) do |f| %>

  <div class="field">
    <p>New lines are seperated by ' || '</p>
    <%= f.text_area :poem, size: "50x10" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>
<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>
</div>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generated Poems</h1>
<h2>Randomly generated Markov-Poems based on Google Searches</h2>
<% @poems.each do |poem| %>
  <%= render poem, index: true %>
<% end %>
<div class="center">
	<%= will_paginate @poems, renderer: BootstrapPagination::Rails %>
</div>
<br>

<%= link_to 'New Poem', new_poem_path %>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form' %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @poem, index: false %>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>